name: Build 2

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      auto_deploy:
        description: Auto deploy to (NONE/UAT/PRD)
        default: NONE
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm i

      - name: Clone rmg-templates repo
        run: git clone https://wongchito:${{ secrets.ACCESS_TOKEN }}@github.com/railmapgen/rmg-templates.git

      - name: Migrate templates
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          npm test -- --watchAll=false ./src/template-migration.test.tsx
          cp -r templates/ rmg-templates/public/resources/
          cd rmg-templates
          git add .
          git commit -m '#2 Migrate templates from RMG'
          git push